/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 E:\MRaza-DigiSol\AR-Initiative\Gallery-three.js\gallery-with-react\gallery\public\rings\ruby-ring.glb 
Author: automicgoldapril (https://sketchfab.com/automicgoldapril)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/au-50949-af0388fdd9894b73a62ab95e9340fe19
Title: AU-50949
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RingThreeModel(props) {
  const { nodes, materials } = useGLTF('/ruby-ring.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.002, 0.002]} rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <mesh geometry={nodes.Object_1_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Diamond_Round_Material_2_0.geometry} material={materials.Material_2} />
          <mesh geometry={nodes.Diamond_Round_2_Material_2_0.geometry} material={materials.Material_2} />
          <mesh geometry={nodes.Diamond_Round_3_Material_2_0.geometry} material={materials.Material_2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ruby-ring.glb')
