/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 E:\MRaza-DigiSol\AR-Initiative\Gallery-three.js\gallery-with-react\gallery\public\rings\pink-ring.glb 
Author: automicgoldapril (https://sketchfab.com/automicgoldapril)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/au-50091-pink-size-8-16cf8f3804b9465aa98ec296919bdf43
Title: AU-50091 Pink Size 8
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RingFiveModel(props) {
  const { nodes, materials } = useGLTF('/pink-ring.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.001]} rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <mesh geometry={nodes.Diamond_Round_09_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Diamond_Round_2_08_0.geometry} material={materials.material_1} />
          <mesh geometry={nodes.Diamond_Round_3_03_0.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Diamond_Round_4_07_0.geometry} material={materials.material_3} />
          <mesh geometry={nodes.Diamond_Round_5_05_0.geometry} material={materials.material_4} />
          <mesh geometry={nodes.Diamond_Round_6_06_0.geometry} material={materials.material_5} />
          <mesh geometry={nodes.Diamond_Round_7_01_0.geometry} material={materials.material_6} />
          <mesh geometry={nodes.Diamond_Round_8_02_0.geometry} material={materials.material_7} />
          <mesh geometry={nodes.Diamond_Round_9_04_0.geometry} material={materials.material_8} />
          <mesh geometry={nodes.Object_1_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pink-ring.glb')
