/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 E:\MRaza-DigiSol\AR-Initiative\Gallery-three.js\gallery-with-react\gallery\public\rings\ring-1.glb 
Author: automicgoldapril (https://sketchfab.com/automicgoldapril)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/au-48213-v3-9215821f8f1b4d2d8dfb8b3db4296e47
Title: AU-48213 V3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RingOneModel(props) {
  const { nodes, materials } = useGLTF('/rings/ring-1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.001, 0.001]} rotation={[-Math.PI, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <mesh geometry={nodes['Object_1_Yellow_Gold-8508952d-1574-41b6-8512-d7f9eb00d480_0'].geometry} material={materials['Yellow_Gold-8508952d-1574-41b6-8512-d7f9eb00d480']} />
          <mesh geometry={nodes['Object_2_White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324_0'].geometry} material={materials['White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324']} />
          <mesh geometry={nodes['Object_3_White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324_2_0'].geometry} material={materials['White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324_2']} />
          <mesh geometry={nodes['Object_4_Rose_Gold-59fc2441-46da-4b59-b8b9-137be5e2ac08_0'].geometry} material={materials['Rose_Gold-59fc2441-46da-4b59-b8b9-137be5e2ac08']} />
          <mesh geometry={nodes.Object_5_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_6_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_7_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_9_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_10_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_11_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes.Object_12_WhiteMetal_0.geometry} material={materials.WhiteMetal} />
          <mesh geometry={nodes['Object_13_Rose_Gold-59fc2441-46da-4b59-b8b9-137be5e2ac08_2_0'].geometry} material={materials['Rose_Gold-59fc2441-46da-4b59-b8b9-137be5e2ac08_2']} />
          <mesh geometry={nodes['Object_14_White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324_3_0'].geometry} material={materials['White_Gold-b46dab22-34ed-4666-af9c-908cd8a75324_3']} />
          <mesh geometry={nodes.Diamond_Round_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Round_2_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Round_3_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Round_4_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Round_5_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Round_6_Material_8_0.geometry} material={materials.Material_8} />
          <mesh geometry={nodes.Diamond_Cushion_Material_8_0.geometry} material={materials.Material_8} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rings/ring-1.glb')
