/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 E:\MRaza-DigiSol\AR-Initiative\Gallery-three.js\gallery-with-react\gallery\public\rings\simple-ring.glb 
Author: automicgoldapril (https://sketchfab.com/automicgoldapril)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/au-50751-162fef4d252f4986ba0b6ae5acaf02ee
Title: AU-50751
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RingTowModel(props) {
  const { nodes, materials } = useGLTF('/rings/simple-ring.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Scene_-_Root']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Scene_-_Root']} />
      </group>
    </group>
  )
}

useGLTF.preload('/rings/simple-ring.glb')
